### ISSUE TITLE
Reading with the specified scheme does not work

### ISSUE THREAD

**Issue by MrSandmanRUS** [ytsaurus/ytsaurus-spyt#12]
Currently, reading with the specified scheme does not work. For example, we have a yt table where one of the columns is of the int type, and we want to immediately read it as a string.

How to reproduce:
val sourceDF = spark.read
      .schema(schema)
      .yt(cfg.source_yt)

Expected behavior:
When reading, you can immediately specify the desired scheme that you want to use.

**Comment by ykuc** [comment]
if The logic is the same for reading yson, It would be great

**Comment by Alexvsalexvsalex** [comment]
The feature was added in the new 2.2.0 version. [commit](https://github.com/ytsaurus/ytsaurus-spyt/commit/0bfc56a8f2c10ae2cfe8ef5b2895df3721049174)

**Comment by ykuc** [comment]
@Alexvsalexvsalex Will this logic work with yson?
