### ISSUE TITLE
Support hive-style partitioning when writing.

### ISSUE THREAD

**Issue by paulpaul1076** [ytsaurus/ytsaurus-spyt#17]
Looking at this link: https://ytsaurus.tech/docs/en/user-guide/data-processing/spyt/best-practices

It seems like spyt is only able to **read** data partitioned using hive-style partitioning. 

Could you also please add support to **write** yt tables using hive style partitioning?

Also please add support for this behavior: `spark.sql.sources.partitionOverwriteMode=dynamic`.

**Comment by Alexvsalexvsalex** [comment]
This feature was [added](https://github.com/ytsaurus/ytsaurus-spyt/commit/b4391e9f153f695ae9f0bd3f2a746860432c586a).
It will be available in the next release

**Comment by paulpaul1076** [comment]
When is the next release?

**Comment by alextokarew** [comment]
> When is the next release?

I think we'll release a new version within 2 or three weeks.
