### ISSUE TITLE
Write spark StringType columns as Utf8 YTsaurus type

### ISSUE THREAD

**Issue by alextokarew** [ytsaurus/ytsaurus-spyt#21]
It is needed to support writing Spark dataframes with StringType columns to YTsaurus tables with Utf8 type columns. Two ways should be supported:

1. `df.write.option("string_to_utf8", "true").yt("//path/to/table")` to convert all string columns to Utf8 type on writing;
2. `import yt.type_info as ti; df.write.schema_hint({"some_string_column": ti.Utf8})` to convert explicitly specified fields to utf8

**Comment by alextokarew** [comment]
@faucct I think we've implemented it. Please link appropriate commit to this Issue and close it.

**Comment by faucct** [comment]
https://github.com/ytsaurus/ytsaurus-spyt/pull/26
