### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by nizhikov** [ytsaurus/ytsaurus-spyt#3]
Looks like now, there are now test environment (Docker for YT or similar) to run ytsaurus-spyt tests locally.
Can you, please, provide one?

**Comment by alextokarew** [comment]
You can use local YTsaurus cluster in Docker as described here: https://ytsaurus.tech/docs/overview/try-yt#using-docker
When starting local YTsaurus you should enable at least one RPC proxy. This can be done with parameter `--rpc-proxy-count 1`

An example commands for running unit tests from ytsaurus-spyt root:
```
wget https://raw.githubusercontent.com/ytsaurus/ytsaurus/main/yt/docker/local/run_local_cluster.sh
bash run_local_cluster.sh --rpc-proxy-count 1
sbt test
bash run_local_cluster.sh --stop
```

**Comment by nizhikov** [comment]
Thanks. 

Tests runs like a charm.
This a script to run - may be helpfull for the next contributors:

```
#!/bin/bash
export YT_SRC=/path/to/ytsarusu/src/

$YT_SRC/yt/docker/local/run_local_cluster.sh --stop
$YT_SRC/yt/docker/local/run_local_cluster.sh --rpc-proxy-count 1
sbt test
$YT_SRC/yt/docker/local/run_local_cluster.sh --stop
```
