### ISSUE TITLE
spark-launch-yt not use parameter spark-cluster-version

### ISSUE THREAD

**Issue by ykuc** [ytsaurus/ytsaurus-spyt#38]
When I create cluster, I add a spark-cluster-version parameter for spark-launch-yt. 

But this parameter was not used. 
spark-launch-yt use version of ytsaurus-spyt

Maybe delete the parameter or add alerts if the version of ytsaurus-spyt != spark-cluster-version parameter

**Comment by alextokarew** [comment]
`--spark-cluster-version` was removed in spyt 2.0.0. Use `--spyt-version` instead
